
/*
#include "defs.h"

        
DMAConfig test_net_layer_0_wm_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 100,
         } ,{  rd_addr : 100,
        wr_addr : 100,
        size : 200,
         } ,{  rd_addr : 200,
        wr_addr : 200,
        size : 300,
         } , };
    
        
FMRoundConfig test_net_layer_0_fm_config[] = 
            { {  shape : {  height : 10,
        width : 10,
        channel : 10,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 2,
        left : 3,
        right : 4,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 100,
        step : 200,
        loop : 2,
         },
         } ,{  shape : {  height : 10,
        width : 10,
        channel : 10,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 2,
        left : 3,
        right : 4,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 200,
        rd_addr : 200,
        size : 100,
        step : 200,
        loop : 3,
         },
         } , };
    
        
DMAConfig test_net_layer_0_ppu_bbqs_bf_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 100,
         } ,{  rd_addr : 100,
        wr_addr : 100,
        size : 200,
         } ,{  rd_addr : 200,
        wr_addr : 200,
        size : 300,
         } , };
    
        
DMAConfig test_net_layer_0_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 100,
         } ,{  rd_addr : 100,
        wr_addr : 100,
        size : 200,
         } ,{  rd_addr : 200,
        wr_addr : 200,
        size : 300,
         } , };
    
        
DMAConfig test_net_layer_0_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 100,
         } ,{  rd_addr : 100,
        wr_addr : 100,
        size : 200,
         } ,{  rd_addr : 200,
        wr_addr : 200,
        size : 300,
         } , };
    
        
LayerConfig test_net_layer[] = 
            { {  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 1024,
        dma : {  dma_length : 3,
        dma : test_net_layer_0_wm_dma_dma,
         },
         },
				 fm : {  loop:1,
					config_length : 2,
        config : test_net_layer_0_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 1024,
        bf : {  dma : {  dma_length : 3,
        dma : test_net_layer_0_ppu_bbqs_bf_dma_dma,
         },
         },
        bm : {  loop : 1024,
        dma : {  dma_length : 3,
        dma : test_net_layer_0_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : True,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 1,
        step : 1,
         },
        wb : {  dma : {  dma_length : 3,
        dma : test_net_layer_0_ppu_wb_dma_dma,
         },
         },
         },
         } , };
    
        
NetConfig net_config = 
            {  layer_length : 1,
        layer : test_net_layer,
         };
						
DMAConfig net_loads[] = { {
		rd_addr: 0,
		wr_addr:	100,
		size:		200
}, };
DMAGroupConfig net_load = {
	dma_length : 1,
	dma: net_loads
};

IOConfig io_config = {
	net_load: {
	dma_length : 1,
	dma: net_loads
},
	feature_load: {
	dma_length : 1,
	dma: net_loads
},
	feature_store:	{
	dma_length : 1,
	dma: net_loads
},
};
*/
#include "defs.h"


        
DMAConfig conv1_wm_dma_dma[] = 
            { {  rd_addr : 33554432,
        wr_addr : 0,
        size : 3456,
         } , };
    
        
FMRoundConfig conv1_fm_config[] = 
            { {  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 1,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 96,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 32,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 96,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 160,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 224,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 288,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 352,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 416,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 480,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 544,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 608,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 672,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 736,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 800,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 864,
        size : 128,
        step : 1024,
        loop : 1,
         },
         } ,{  shape : {  height : 34,
        width : 4,
        channel : 1,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 1,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 928,
        size : 96,
        step : 1024,
        loop : 1,
         },
         } , };
    
        
DMAConfig conv1_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67108864,
        wr_addr : 0,
        size : 512,
         } , };
    
        
DMAConfig conv1_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 16384,
        size : 16384,
         } , };
    
        
DMAConfig conv2_wm_dma_dma[] = 
            { {  rd_addr : 33572864,
        wr_addr : 0,
        size : 114432,
         } , };
    
        
FMRoundConfig conv2_fm_config[] = 
            { {  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 1,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16384,
        size : 48,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16400,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16432,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16464,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16496,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16528,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16560,
        size : 64,
        step : 256,
        loop : 4,
         },
         } ,{  shape : {  height : 18,
        width : 4,
        channel : 4,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 1,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16592,
        size : 48,
        step : 256,
        loop : 4,
         },
         } , };
    
        
DMAConfig conv2_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67109376,
        wr_addr : 0,
        size : 1536,
         } , };
    
        
DMAConfig conv2_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 12288,
         } , };
    
        
DMAConfig conv3_wm_dma_dma[] = 
            { {  rd_addr : 33794048,
        wr_addr : 0,
        size : 495776,
         } , };
    
        
FMRoundConfig conv3_fm_config[] = 
            { {  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 1,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 16,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 8,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 16,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 24,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 32,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 40,
        size : 24,
        step : 64,
        loop : 12,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 12,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 1,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 48,
        size : 16,
        step : 64,
        loop : 12,
         },
         } , };
    
        
DMAConfig conv3_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67110912,
        wr_addr : 0,
        size : 3072,
         } , };
    
        
DMAConfig conv3_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 12288,
        size : 24576,
         } , };
    
        
DMAConfig conv4_wm_dma_dma[] = 
            { {  rd_addr : 35121152,
        wr_addr : 0,
        size : 1125408,
         } , };
    
        
FMRoundConfig conv4_fm_config[] = 
            { {  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 1,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12288,
        size : 16,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12288,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12296,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12304,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12312,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12320,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12328,
        size : 24,
        step : 64,
        loop : 24,
         },
         } ,{  shape : {  height : 10,
        width : 3,
        channel : 24,
         },
        kernel : 3,
        stride : 1,
        pooling : 1,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 1,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 12336,
        size : 16,
        step : 64,
        loop : 24,
         },
         } , };
    
        
DMAConfig conv4_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67113984,
        wr_addr : 0,
        size : 2048,
         } , };
    
        
DMAConfig conv4_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 36864,
        size : 16384,
         } , };
    
        
DMAConfig conv5_wm_dma_dma[] = 
            { {  rd_addr : 36890624,
        wr_addr : 0,
        size : 756832,
         } , };
    
        
FMRoundConfig conv5_fm_config[] = 
            { {  shape : {  height : 10,
        width : 4,
        channel : 16,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 1,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 36864,
        size : 24,
        step : 64,
        loop : 16,
         },
         } ,{  shape : {  height : 10,
        width : 4,
        channel : 16,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 36872,
        size : 32,
        step : 64,
        loop : 16,
         },
         } ,{  shape : {  height : 10,
        width : 4,
        channel : 16,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 36888,
        size : 32,
        step : 64,
        loop : 16,
         },
         } ,{  shape : {  height : 10,
        width : 4,
        channel : 16,
         },
        kernel : 3,
        stride : 1,
        pooling : 2,
        padding : {  top : 1,
        bottom : 1,
        left : 0,
        right : 1,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 36904,
        size : 24,
        step : 64,
        loop : 16,
         },
         } , };
    
        
DMAConfig conv5_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67116032,
        wr_addr : 0,
        size : 2048,
         } , };
    
        
DMAConfig conv5_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 4096,
         } , };
    
        
DMAConfig fc1_wm_dma_dma[] = 
            { {  rd_addr : 38070272,
        wr_addr : 0,
        size : 1868384,
         } , };
    
        
FMRoundConfig fc1_fm_config[] = 
            { {  shape : {  height : 1,
        width : 1,
        channel : 256,
         },
        kernel : 1,
        stride : 1,
        pooling : 1,
        padding : {  top : 0,
        bottom : 0,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 1,
        step : 1,
        loop : 256,
         },
         } , };
    
        
DMAConfig fc1_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67118080,
        wr_addr : 0,
        size : 8192,
         } , };
    
        
DMAConfig fc1_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 4096,
        size : 1024,
         } , };
    
        
DMAConfig fc2_wm_dma_dma[] = 
            { {  rd_addr : 46458880,
        wr_addr : 0,
        size : 559552,
         } , };
    
        
FMRoundConfig fc2_fm_config[] = 
            { {  shape : {  height : 1,
        width : 1,
        channel : 64,
         },
        kernel : 1,
        stride : 1,
        pooling : 1,
        padding : {  top : 0,
        bottom : 0,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 4096,
        size : 1,
        step : 1,
        loop : 64,
         },
         } , };
    
        
DMAConfig fc2_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67126272,
        wr_addr : 0,
        size : 8192,
         } , };
    
        
DMAConfig fc2_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 0,
        size : 1024,
         } , };
    
        
DMAConfig fc3_wm_dma_dma[] = 
            { {  rd_addr : 48556032,
        wr_addr : 0,
        size : 8032,
         } , };
    
        
FMRoundConfig fc3_fm_config[] = 
            { {  shape : {  height : 1,
        width : 1,
        channel : 64,
         },
        kernel : 1,
        stride : 1,
        pooling : 1,
        padding : {  top : 0,
        bottom : 0,
        left : 0,
        right : 0,
         },
        round_read_times : 0,
        round_read_sig : 0,
        dma : {  wr_addr : 0,
        rd_addr : 0,
        size : 1,
        step : 1,
        loop : 64,
         },
         } , };
    
        
DMAConfig fc3_ppu_bbqs_bm_dma_dma[] = 
            { {  rd_addr : 67134464,
        wr_addr : 0,
        size : 128,
         } , };
    
        
DMAConfig fc3_ppu_wb_dma_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 1024,
        size : 16,
         } , };
    
        
LayerConfig alexnet_cifar_layer[] = 
            { {  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 64,
        dma : {  dma_length : 1,
        dma : conv1_wm_dma_dma,
         },
         },
        fm : {  config_length : 16,
        config : conv1_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 1024,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 1024,
        dma : {  dma_length : 1,
        dma : conv1_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : True,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 16,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : conv1_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 16,
        dma : {  dma_length : 1,
        dma : conv2_wm_dma_dma,
         },
         },
        fm : {  config_length : 8,
        config : conv2_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 256,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 256,
        dma : {  dma_length : 1,
        dma : conv2_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : True,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 8,
        step : 8,
         },
        wb : {  dma : {  dma_length : 1,
        dma : conv2_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 8,
        dma : {  dma_length : 1,
        dma : conv3_wm_dma_dma,
         },
         },
        fm : {  config_length : 8,
        config : conv3_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 128,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 128,
        dma : {  dma_length : 1,
        dma : conv3_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : False,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 8,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : conv3_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 8,
        dma : {  dma_length : 1,
        dma : conv4_wm_dma_dma,
         },
         },
        fm : {  config_length : 8,
        config : conv4_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 128,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 128,
        dma : {  dma_length : 1,
        dma : conv4_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : False,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 8,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : conv4_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 3,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 8,
        dma : {  dma_length : 1,
        dma : conv5_wm_dma_dma,
         },
         },
        fm : {  config_length : 4,
        config : conv5_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 128,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 128,
        dma : {  dma_length : 1,
        dma : conv5_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : True,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 4,
        step : 8,
         },
        wb : {  dma : {  dma_length : 1,
        dma : conv5_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 1,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 1,
        dma : {  dma_length : 1,
        dma : fc1_wm_dma_dma,
         },
         },
        fm : {  config_length : 1,
        config : fc1_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 16,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 16,
        dma : {  dma_length : 1,
        dma : fc1_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : False,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 1,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : fc1_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 1,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 1,
        dma : {  dma_length : 1,
        dma : fc2_wm_dma_dma,
         },
         },
        fm : {  config_length : 1,
        config : fc2_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 16,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 16,
        dma : {  dma_length : 1,
        dma : fc2_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : True,
         },
        pool : {  en : False,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 1,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : fc2_ppu_wb_dma_dma,
         },
         },
         },
         } ,{  pe : {  pe : {  fsign : True,
         },
        ce : {  kernel : 1,
        stride : 1,
         },
        comp : {  en : True,
         },
         },
        wm : {  loop : 1,
        dma : {  dma_length : 1,
        dma : fc3_wm_dma_dma,
         },
         },
        fm : {  config_length : 1,
        config : fc3_fm_config,
         },
        ppu : {  bbqs : {  sc_sign : True,
        sc_en : False,
        loop : 16,
        bf : {  dma : {  dma_length : 0,
        dma : NULL,
         },
         },
        bm : {  loop : 16,
        dma : {  dma_length : 1,
        dma : fc3_ppu_bbqs_bm_dma_dma,
         },
         },
         },
        act : {  en : False,
         },
        pool : {  en : False,
        sign : True,
        kernel : 0,
         },
        dc : {  size : 1,
        step : 16,
         },
        wb : {  dma : {  dma_length : 1,
        dma : fc3_ppu_wb_dma_dma,
         },
         },
         },
         } , };
    
        
NetConfig alexnet_cifar = 
            {  layer_length : 8,
        layer : alexnet_cifar_layer,
         };
    
        
DMAConfig net_params_dma[] = 
            { {  rd_addr : 0,
        wr_addr : 33554432,
        size : 3456,
         } ,{  rd_addr : 0,
        wr_addr : 33572864,
        size : 114432,
         } ,{  rd_addr : 0,
        wr_addr : 33794048,
        size : 495776,
         } ,{  rd_addr : 0,
        wr_addr : 35121152,
        size : 1125408,
         } ,{  rd_addr : 0,
        wr_addr : 36890624,
        size : 756832,
         } ,{  rd_addr : 0,
        wr_addr : 38070272,
        size : 1868384,
         } ,{  rd_addr : 0,
        wr_addr : 46458880,
        size : 559552,
         } ,{  rd_addr : 0,
        wr_addr : 48556032,
        size : 8032,
         } ,{  rd_addr : 0,
        wr_addr : 67108864,
        size : 512,
         } ,{  rd_addr : 0,
        wr_addr : 67109376,
        size : 1536,
         } ,{  rd_addr : 0,
        wr_addr : 67110912,
        size : 3072,
         } ,{  rd_addr : 0,
        wr_addr : 67113984,
        size : 2048,
         } ,{  rd_addr : 0,
        wr_addr : 67116032,
        size : 2048,
         } ,{  rd_addr : 0,
        wr_addr : 67118080,
        size : 8192,
         } ,{  rd_addr : 0,
        wr_addr : 67126272,
        size : 8192,
         } ,{  rd_addr : 0,
        wr_addr : 67134464,
        size : 128,
         } , };
    
        
IOConfig alexnet_cifar_io = 
            {  net_load : {  dma_length : 16,
        dma : net_params_dma,
         },
        feature_load : {  rd_addr : 0,
        wr_addr : 0,
        size : 16384,
         },
        feature_store : {  rd_addr : 1024,
        wr_addr : 0,
        size : 16,
         },
         };
    
